name: Chore
description: A task or activity that doesn't change behaviour or fix a bug
labels: 'chore'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "What needs to be accomplished?"
      placeholder: "ie: upgrade a gem, add new chemimicals, etc."
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: "Is any work out of scope?"
      placeholder: "ie: changing the behaviour of the app, fixing a bug, etc."
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "ie: this was requested by a customer, it allows us to start work on another issue, etc."
    validations:
      required: false
