name: Chore
about: A task or activity that doesn't change behaviour or fix a bug
labels: 'chore'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: description
    attributes:
      label: Description
      description: "What needs to be accomplished?"
      placeholder: "A short description of the task (ie: upgrade a gem, add new chemimicals, etc.)"
    validations:
      required: true
